### ISSUE TITLE
RFE: Improve renaming of a file containing multiple episodes

### ISSUE THREAD

**Issue by ludi113** [bugwelle/MediaElch#31]
Hi, 

First of all, I would like to thank you for the contribution you are giving in maintaining and improving MediaElch. 

Sometimes, a TV channel broadcasts two or more episodes of a TV Show without showing the theme of the show between the episodes. In this case, it would be odd to split the file containing the recording in several files containing only one episode, as only the first episode contains the TV Show theme. 

As far as I know, kodi understands for example strings like S01E01E02 for a file containing the first two episodes of the first season of a TV Show. 

Would it be possible to enhance the renamer in MediaElch to rename such files to include the subtitles of all the episodes available in the file? 

This might perhaps be already possible, but the links to the explanations about the renamer are both broken: the link in MediaElch 2.4 as well as the link in MediaElch 2.6. 

Thanks in advance for anything you can do about the issue.

**Comment by ludi113** [comment]
This bug thread can be closed, as I submitted a more detailed version here: 
https://github.com/Komet/MediaElch/issues/675

**Comment by bugwelle** [comment]
Oh, sorry for not answering! I totally forgot about this as it's not in the main repository. Thanks for opening the issue at github.com/Komet/MediaElch

**Comment by ludi113** [comment]
No problem. Thanks again for all the efforts you put into maintaining and improving MediaElch.
